function f = feature3(img, r, c, width, height)
    f = response(img, r, c, width/3 - 1, height-1)...
        - response(img, r, c + width/3, width/3 - 1, height-1)...
        + response(img, r, c + 2 * width/3, width/3 - 1, height - 1);
end