function f = feature5(img, r, c, width, height)
    f = response(img, r, c, width/2 -1, height/2 -1)...
        - response(img, r, c +width/2, width/2 -1, height/2 -1)...
        + response(img, r+height/2, c, width/2 -1, height/2 -1)...
        - response(img, r+height/2, c+width/2, width/2-1, height/2-1);
end