function f = feature4(img, r, c, width, height)
    f = response(img, r, c, width-1, height/3 -1)...
        - response(img, r + height/3, c, width-1, height/3 - 1)...
        + response(img, r + 2 *height/3, c, width-1, height/3 -1);
end